---
###############################################################################
# Configure Linux auditing
###############################################################################

- name: Install Auditd packages
  ansible.builtin.apt:
    name: "{{ security_auditd_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Deploy managed Auditd rules
  ansible.builtin.copy:
    dest: /etc/audit/rules.d/99-security.rules
    owner: root
    group: root
    mode: "0640"
    content: |
      # Managed by Ansible.
      # Local changes will be overwritten.

      {% for audit_rule in security_auditd_rules %}
      {{ audit_rule }}
      {% endfor %}
  notify: Load Auditd rules

- name: Ensure Auditd is enabled and running
  ansible.builtin.service:
    name: auditd
    enabled: true
    state: started
  when:
    - not ansible_check_mode
