---
###############################################################################
# Configure Chrony
###############################################################################

- name: Install Chrony packages
  ansible.builtin.apt:
    name: "{{ security_chrony_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Deploy Chrony configuration
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart Chrony

- name: Ensure Chrony is enabled and running
  ansible.builtin.service:
    name: chrony
    enabled: true
    state: started
  when:
    - not ansible_check_mode
