---
###############################################################################
# Validate security role prerequisites
###############################################################################

- name: Verify supported operating system
  ansible.builtin.assert:
    that:
      - ansible_os_family == "Debian"
    fail_msg: >
      The security role currently supports only Debian-based operating systems.
    success_msg: >
      Operating system is supported.

- name: Verify package manager
  ansible.builtin.assert:
    that:
      - ansible_pkg_mgr == "apt"
    fail_msg: >
      This role currently supports only the APT package manager.
    success_msg: >
      Package manager is supported.
