---
common_system_timezone: America/Monterrey

common_packages:
  - curl
  - git
  - htop
  - nano
  - unzip
  - vim

###############################################################################
# Security role
###############################################################################

security_manage_packages: false
security_manage_unattended_upgrades: true
security_manage_fail2ban: true

security_manage_auditd: true
security_manage_chrony: true
security_manage_sysctl: true
security_manage_firewall: true
security_firewall_ssh_source: 10.10.60.0/24
