---
###############################################################################
# Common Role Handlers
#
# Service and system handlers notified by common role tasks.
###############################################################################
