---
all:
  children:
    linux:
      children:
        controllers:
        hypervisors:
        raspberry_pi:

    infrastructure_services:
      children:
        pihole_servers:
        homeassistant_servers:
        docker_hosts:

    monitoring_and_security:
      children:
        security_monitoring:

    network_infrastructure:
      children:
        network_devices:

    controllers:
      hosts:
        tf-controller:
          ansible_connection: local
          ansible_user: notadm1n

    hypervisors:
      hosts:
        pve-k9:
          ansible_host: 10.10.60.3
          ansible_user: root
          ansible_connection: ssh

    raspberry_pi:
      hosts:
        rpi4-pihole:
          ansible_host: 10.10.30.53
          ansible_user: pi
          ansible_connection: ssh

        rpi4-homeassistant:
          ansible_host: 10.10.30.40
          ansible_user: notadm1n
          ansible_connection: ssh

    pihole_servers:
      hosts:
        rpi4-pihole:

    homeassistant_servers:
      hosts:
        rpi4-homeassistant:

    security_monitoring:
      hosts:
        wazuh:
        securityonion:
        velociraptor:

    network_devices:
      hosts:
        er605:
        unifi-switch:

    docker_hosts:
      hosts:

    development:
      hosts:

    future:
      hosts:
