---
all:
  children:
    linux:
      children:
        ubuntu_servers:
          hosts:
            tf-controller:
              ansible_connection: local
              ansible_user: notadm1n

          vars:
            ansible_connection: ssh

    proxmox_hosts:
      hosts:
        pve-k9:
          ansible_host: 10.10.60.3
          ansible_user: root

      vars:
        ansible_connection: ssh
