---
###############################################################################
# Hostname Management
#
# Configure the system hostname when enabled.
###############################################################################

- name: Configure system hostname
  ansible.builtin.hostname:
    name: "{{ common_hostname }}"
  when: common_manage_hostname | bool
  tags:
    - common
    - hostname
