---
###############################################################################
# Manage system timezone
###############################################################################

- name: Get current timezone
  ansible.builtin.command:
    argv:
      - timedatectl
      - show
      - --property=Timezone
      - --value
  register: common_current_timezone
  changed_when: false
  when: common_manage_timezone | bool

- name: Configure system timezone
  ansible.builtin.command:
    argv:
      - timedatectl
      - set-timezone
      - "{{ common_system_timezone }}"
  changed_when: true
  when:
    - common_manage_timezone | bool
    - common_current_timezone.stdout != common_system_timezone
