---
###############################################################################
# Security role handlers
###############################################################################

- name: Restart Fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  when:
    - not ansible_check_mode

- name: Load Auditd rules
  ansible.builtin.command:
    cmd: augenrules --load
  changed_when: true
  when:
    - not ansible_check_mode

- name: Restart Chrony
  ansible.builtin.service:
    name: chrony
    state: restarted
  when:
    - not ansible_check_mode
